abstract class CreateContentStates{}
class CreateContentInitialState extends CreateContentStates{}
class CreateContentPickImageState extends CreateContentStates{}
class ChangeAudienceValueState extends CreateContentStates{}
class ChangeContentTypeValueState extends CreateContentStates{}
class ChangeContentBrandTypeValueState extends CreateContentStates{}
class ChangeContentStockAvailabilityValueState extends CreateContentStates{}
class ChangeUsesTypeValueState extends CreateContentStates{}
class ChangeContentPriceTypeValueState extends CreateContentStates{}
class ChangeAfghanValueState extends CreateContentStates{}