abstract class CreatePageScreenState{}
class CreatePageInitialState extends CreatePageScreenState{}
class CreatePagePickImageState extends CreatePageScreenState{}

class ChangeCreatePageTypeState extends CreatePageScreenState{}
class ChangeProductTypeValueState extends CreatePageScreenState{}
class ChangeServiceTypeValueState extends CreatePageScreenState{}
class ChangeStoryHeaderLineValueState extends CreatePageScreenState{}


class ChangeAudienceValueState extends CreatePageScreenState{}
class ChangeHiringValueState extends CreatePageScreenState{}

class ChangeSkillTalentTypeValueState extends CreatePageScreenState{}
class ChangeContentTypeValueState extends CreatePageScreenState{}
class ChangeBrandTypeValueState extends CreatePageScreenState{}
class ChangeStockAvailabilityValueState extends CreatePageScreenState{}
class ChangeUsesTypeValueState extends CreatePageScreenState{}
class ChangePriceTypeValueState extends CreatePageScreenState{}
class ChangeAfghanValueState extends CreatePageScreenState{}
class ChangeDisclaimerValueState extends CreatePageScreenState{}
class ChangeImaginativeYearValueState extends CreatePageScreenState{}
class ChangeStoryFeaturedProductValueState extends CreatePageScreenState{}